language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: RC9W4K8XsyPZeJ+ZDA6liJzbovyu8AjvhEtu9FOyykZUUEoI5Rj5GBqshFVogm/Fpkvr6W0klBZHRsyhx1AlFx3EB1v16A4CMqGyMTwzu/r9lLXQvcVpA8BkWSdz+gACPWQKlkbt7QBlvRAsICvJgdrMGlosPA1gsqy04eNEu6agtZFAJowaCBrzYxndjWLpu5778w6+H54YlxvLKrU2rUWlRK5eN4oB3ndOn38qpAGo7ue9lZTzMMjRKxhjAQFIspujAJSZxqCHWp2v+ImTEnHKljum8dTFvPxbUst8orr2KuXp6lrV9MCv3ZsrV2Z1/VLWEaZSLsGxwmazbYitjz9f0roe7K97YzkYC6b/Lv7+HBfO41WrNj7XnaNStc+pkjw8eiAm8KWo57/dz6wVVbMWz/vTejxWycg9ngi4LLs9bPJ7JFXSuMnsukDXM/nQmXqyWxHvaSq6TtDwOZl16N8ZP/fbiLzwKSUPn+vu/B9GGjytZuhc5phk/0Nn7VykvRZl6XMvu0WFcRfLeioynIVia+3FLTNGBXhHukhnWJAcooQwGi0kDZXp0LUNwlzcuvVl6tbR1sEKxLmM36MsjHE2//3BXxdHfBtw7f0M0DZ4+VAUtKHbF/SJ4F2dQoiK/sep2LEQjrtJQrXIrpaIyVo3M2hYZlAdT59dPklWWLM=
  app: myownblogposts
  on:
    repo: ericpcho/blogPostsApi
